name: Push Docker Image
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
        run:
          docker login -u $DOCKER_USERNAME -p $DOCKER_PWD
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag adi4196/us-mobile-service:latest
      - name: Push the Docker Image   
        run: docker push adi4196/us-mobile-service:latest
        
