name: Push Docker Image
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/usmobile/my-image-name:$(date +%s)
          docker run ghcr.io/usmobile/my-image-name:$(date +%s)
          docker push ghcr.io/usmobile/my-image-name:$(date +%s)
        
